### ISSUE TITLE
Bitbucket Server support

### ISSUE THREAD

**Issue by sa-spag** [fluxcd/flux-recv#12]
Hey there 👋 

We're using Bitbucket Server and we'd like flux-recv to support it. Bitbucket Server (and probably Cloud too) supports push events webhooks ([see here](https://confluence.atlassian.com/bitbucketserver067/managing-webhooks-in-bitbucket-server-979426856.html)).
I could implement the handler myself once I have time but if anyone wants to jump in, feel free.

**Comment by squaremo** [comment]
Hello!

> Bitbucket Server (and probably Cloud too) supports push events webhooks

They both do, yes -- but using different formats :man_facepalming: 

I have the code for the Bitbucket Cloud webhooks close at hand; if you (or anyone!) want to contribute code for Bitbucket Server, I would certainly be grateful!

**Comment by goldsam** [comment]
@squaremo 
> I have the code for the Bitbucket Cloud webhooks close at hand; 

If that implies you have existing code, I would be happy to help work on it.  If not, let me know and I will get started. My team is anxious to have our gitops cycles be more responsive using Bitbucket Cloud 😄

**Comment by squaremo** [comment]
@goldsam #13 adds Bitbucket Cloud support (or so I claim; I did try it in another setting). If you want to try it with your setup that would be :top:

**Comment by goldsam** [comment]
I created a [build against master at commit fb34a23](https://hub.docker.com/layers/goldsam/flux-recv/master-fb34a23/images/sha256-468af8ccb340301c418ac85018e281861b69e39656b6b11e07acf897e4346d41) which I have been testing with today. It seems to work great, however all of my pushes consisted of only a few commits. Great work and thank you! I look forward to the next official release. 😊

**Comment by squaremo** [comment]
> I look forward to the next official release.

Just pushed fluxcd/flux-recv:0.3.0
