### ISSUE TITLE
Google Cloudbuild Support

### ISSUE THREAD

**Issue by chainlink** [fluxcd/flux-recv#15]
This could be supported in 1 of 2 ways:
- Pub/sub integration (listen for GCB events)
or 
- wire up a google cloud function with listens for the pub/sub event and pushes to flux-recv via http (more natural in keeping with the webhook idea)

**Comment by chainlink** [comment]
Potentially could hack by having the gcloudbuild function 'speak' the dockerhub format and use that handler instead.

**Comment by squaremo** [comment]
> Potentially could hack by having the gcloudbuild function 'speak' the dockerhub format and use that handler instead.

That'd certainly be a decent interim solution, if it can be made to work.

**Comment by dmccaffery** [comment]
@chainlink FYI: should be able to use a pubsub push subscription instead of a pull subscription to wire up the GCB events directly to the webhook receiver without requiring an intermediate GCF. I'm looking into implementing events for GCR and would like to implement google auth token validation, which would apply to GCB events as well.

Which specific events were you looking to handle?

**Comment by chainlink** [comment]
Specifically successful build notifications, which would poke flux to update it's internal cache vs waiting for a registry poll.

**Comment by dmccaffery** [comment]
Do you publish to GCR?

**Comment by chainlink** [comment]
yep

**Comment by dmccaffery** [comment]
Gotcha. So, maybe I lack the understanding of your use case but what I *think* you're after is "hey flux... I pushed something to the registry... update NOW". If that's the case, you should benefit from GCR push notifications without relying on notifications from GCB.

I plan to attack this tomorrow. Assuming @squaremo doesn't poo poo the PR, we should both be in the clear. :)

**Comment by chainlink** [comment]
I didn't know GCR notifications were a thing, that sounds great!

**Comment by hiddeco** [comment]
Given the above messages, has this been superseded by #18 and #20?

**Comment by dmccaffery** [comment]
Yes.

**Comment by hiddeco** [comment]
Thanks for the confirmation :tulip:
