### ISSUE TITLE
Sync only with webhooks

### ISSUE THREAD

**Issue by rdubya16** [fluxcd/flux-recv#16]
I was wondering if there is a way currently to disable scheduled syncing in flux and only use webhooks to trigger the sync? If not seems like a good feature to have for doing things like gating the manifest application by waiting for a webhook.

**Comment by Crevil** [comment]
This flow is error prone to lost webooks. We've had several "incidents" with services using this flow in the past. If GitHub is undergoing an incident and webhooks are delayed every thing is stopped until they resume.

This might be what you'r after, but to me, it's an issue.

**Comment by Crevil** [comment]
I might be missing your use case. Where would the gating actually have an effect?

**Comment by rdubya16** [comment]
Yeah that makes sense. Seems less than ideal in that respect.
