### ISSUE TITLE
feat(images): Quay.io support

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux-recv#25]
With DockerHub and Harbor added we already have a pretty broad list of supported registry vendors. Support for Quay.io is however still missing, and they are known for having a pretty aggressive rate limit in place.

Quay.io sends out a [repository push](https://docs.quay.io/guides/notifications.html) payload in the following format:

```json
{
  "name": "repository",
  "repository": "mynamespace/repository",
  "namespace": "mynamespace",
  "docker_url": "quay.io/mynamespace/repository",
  "homepage": "https://quay.io/repository/mynamespace/repository",
  "updated_tags": [
    "latest"
  ]
}
```

**Comment by JDavis10213** [comment]
@hiddeco I am actually working on an integration with Quay. I have the integration done but haven't had the time to finish the tests and documentation. Once I get those completed I plan on submitting an PR. Here is my fork if you would like to test it out. https://github.com/JDavis10213/flux-recv

**Comment by hiddeco** [comment]
@JDavis10213 awesome! I can't seem to find a commit related to Quay.io in the linked fork however. Did you forget to push the changes, or is it in a branch I didn't spot?

Feel free to open a PR with whatever you have right now, and some pointers on what is missing, and I may be able to either guide you through the tests and documentation or add the missing elements, depending on the amount of time you have available :tulip:

**Comment by JDavis10213** [comment]
> @JDavis10213 awesome! I can't seem to find a commit related to Quay.io in the linked fork however. Did you forget to push the changes, or is it in a branch I didn't spot?
> 
> Feel free to open a PR with whatever you have right now, and some pointers on what is missing, and I may be able to either guide you through the tests and documentation or add the missing elements, depending on the amount of time you have available 🌷

Sorry about that! I hadn't pushed it up. Pushed up now. I will see if I can get the PR together. If you would like to assist please do as I am limited on time this week as I am in the process of migrating services and doing a lot of knowledge transfer for the other team.
