### ISSUE TITLE
Installing with Flux Helm Chart

### ISSUE THREAD

**Issue by shaz1v** [fluxcd/flux-recv#9]
Hey,

We have flux deployed on all of our clusters and have been looking for a way to get the flux git source synced instantly instead of waiting for the 5m interval auto-sync method.

The issue is we have deployed our Flux deployments based on the Helm Chart, we're trying to figure out how to get this to work, without manually modifying the deployment created by Helm.

I was thinking of 2 solutions and would like to know if they are possible:

> Have the flux-recv added as an optional config to the main Flux helm chart

I hope that's on the future plans, but I'm sure it wont be immediate  
>Deploying the flux-recv as an individual deployment, on the same namespace on the flux deployment, notifying it on changes

This seems to be the faster solution, although we couldn't find a parameter or a way to tell the flux-recv that flux isn't available in localhost:3030 and is available via its service at `http://flux:3030`

Thanks! Shahar

**Comment by squaremo** [comment]
The intention is that you can supply the flux API location in the config file, in the field `api:`. So it would look like this:

```yaml
fluxRecvVersion: 1
api: http://flux:3030/api/flux
endpoints:
# ...
```

This will mean you need to expose the flux API in a service (or port-forward from a sidecar?).

If this doesn't work, it's a bug :-)

**Comment by derrickburns** [comment]
@squaremo I think my other issue reflects a similar issue, that it is not apparent how to change the endpoint without reading the code. :)

**Comment by derrickburns** [comment]
FYI https://github.com/micro/go-micro/tree/master/config/source/env looks useful.

**Comment by shaz1v** [comment]
@squaremo thanks, it is working :) closing the issue.
